### ISSUE TITLE
Overlap One Image over Another

### ISSUE THREAD

**Issue by mozgbrasil** [dooman87/imagemagick-docker#15]
Good afternoon my friends

I have the following imagemagick command to overlay images

     composite -gravity Center image_resize.png canvas.png image.png

When I try the following way using its container, it returns an empty image

	docker run -v ~/Imagens:/imgs dpokidov/imagemagick \
	-composite -gravity Center /imgs/image_resize.png /imgs/canvas.png /imgs/$(date +%Y-%m-%d_%H-%M-%S)_image.png

Thank you in advance if you can help

**Comment by dooman87** [comment]
Hey, 

Thanks for creating this. Could you please share the image, so I can reproduce and show the version of the local IM (`composite --version`)?

**Comment by mozgbrasil** [comment]
Follows in

https://drive.google.com/drive/folders/1bqTV4nlLg0E1bn_BBAFBHPvq2bglmwh7?usp=sharing

**Comment by dooman87** [comment]
I think `-composite` flag is different from `composite` entrypoint. The below worked for me:

`docker run -v $(pwd):/imgs --entrypoint=composite dpokidov/imagemagick -gravity Center /imgs/image_resize.png /imgs/canvas.png /imgs/out.png`

**Comment by mozgbrasil** [comment]
I just installed imagemagick and run the following command

    composite -gravity Center image_resize.png canvas.png image.png

Which returned the expected result

Using the container the image is returned with error in the case in black and white

![Captura de tela de 2021-09-22 09-45-10](https://user-images.githubusercontent.com/17202780/134346060-16b1e269-5486-4020-873e-c2a9a50d2158.png)

**Comment by dooman87** [comment]
Looks like an IM bug to me. Just to make sure could you please post `composite -version` output here?

**Comment by mozgbrasil** [comment]
$ composite --version
	Version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
	Copyright: © 1999-2019 ImageMagick Studio LLC
	License: https://imagemagick.org/script/license.php
	Features: Cipher DPC Modules OpenMP 
	Delegates (built-in): bzlib djvu fftw fontconfig freetype heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png tiff webp wmf x xml zlib

**Comment by dooman87** [comment]
Yup, so it seems like an IM bug. I tested it on version 7.0.7-2 and it's working as expected:

`docker run -v $(pwd):/imgs --entrypoint=composite dpokidov/imagemagick:7.0.7-2 -gravity Center /imgs/image_resize.png /imgs/canvas.png /imgs/out.png`

**Comment by mozgbrasil** [comment]
Thank you my friend

**Comment by dooman87** [comment]
I've also opened an issue in IM - https://github.com/ImageMagick/ImageMagick/issues/4271

**Comment by dooman87** [comment]
And it turned out that the latest version of IM needs an extra `-colorspace -sRGB` to make it work.
