### ISSUE TITLE
Release arm64 images for apple M1 mac

### ISSUE THREAD

**Issue by spuder** [dooman87/imagemagick-docker#22]
If you try and use this container on an M1 mac you get this error

```
Status: Downloaded newer image for dpokidov/imagemagick:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

Solutions

1. Use [docker buildx as shown in this blog](https://www.docker.com/blog/multi-arch-images/)

2. If using github actions, you can [make the builds multiplatform by adding the `platform` with stanza](https://github.com/spuder/stl2origin/blob/master/.github/workflows/dockerhub.yaml#L33)

**Comment by dooman87** [comment]
Thanks @spuder for creating that. Looks like it should be easy to do with Github Actions. I don't have ARM machine handy though, would you be able to help with testing?

**Comment by spuder** [comment]
Yes, I have an M1 and I can help test.

**Comment by juanbeniteza** [comment]
I just tested the fedora arm build on my M1 Pro MacBook and it works perfect

**Comment by dooman87** [comment]
The version 7.1.0-20 has both amd64 and arm64 builds. @spuder If you could try one of them that would be great - https://hub.docker.com/r/dpokidov/imagemagick/tags

**Comment by spuder** [comment]
Basic functionality is working on my M1 mac. Thank you. 

```
docker run -it --rm dpokidov/imagemagick:7.1.0-20 --version
Version: ImageMagick 7.1.0-20 Q16-HDRI aarch64 2022-01-15 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5)
Delegates (built-in): fontconfig freetype heic jbig jng jpeg lzma png tiff webp xml zlib
Compiler: gcc (8.3)
```
