### ISSUE TITLE
lcms:  Enable configuration build flag

### ISSUE THREAD

**Issue by eladiogalvez** [dooman87/imagemagick-docker#23]
We detected that set profile option is not working like is exposed in this post:

https://stackoverflow.com/questions/47414462/php-imagick-wont-add-icc-color-profile

It's possible to enable configure/make flag lcms in your image?

**Comment by dooman87** [comment]
Hi,

Thanks a lot for reporting the issue.

Could you please provide some more info if possible:

* What base image did you use (fedora, buster, etc)?
* How we could test it? If you could provide a command with the example image that would be great.

Not sure if it's related, but here https://github.com/Pixboost/transformimgs/blob/master/img/processor/imagemagick.go#L39 we strip all the profiles except `icc` and it works. We run this code on buster variant.

**Comment by eladiogalvez** [comment]
I use the image:

> dpokidov/imagemagick:7.1.0-8-buster

You can test checking delegations:

If it works:
# convert -list configure | grep DELEGATES
DELEGATES     bzlib fontconfig freetype gs jpeg jng jp2 lcms openexr png rsvg tiff x11 xml wmf zlib

If the dpokidov buster image:

# convert -list configure | grep DELEGATES
DELEGATES             fontconfig freetype heic jbig jng jpeg lzma png ps tiff webp xml zlib
DELEGATES             fontconfig freetype heic jbig jng jpeg lzma png tiff webp xml zlib

And also if is possible add the other delegations that are in example and not displayed in buster image will be very useful ;)


>

**Comment by dooman87** [comment]
This should be fixed in 7.1.0-23. @eladiogalvez let me know if you have any issues.
