### ISSUE TITLE
Put DockerHub link here

### ISSUE THREAD

**Issue by doggy8088** [dooman87/imagemagick-docker#36]
I'd like to suggestion you put a [DockerHub link](https://hub.docker.com/r/dpokidov/imagemagick) here:

![image](https://user-images.githubusercontent.com/88981/213729764-95601a3e-2d7c-4268-bf1e-7cf709e40b0b.png)

**Comment by dooman87** [comment]
Thanks! Just added the link. Also, found out that there are verified publishers on Docker Hub now... What an obsession with blue ticks haha
