### ISSUE TITLE
`magick mogrify` command is not working

### ISSUE THREAD

**Issue by rabbygit** [dooman87/imagemagick-docker#39]
I pulled the latest image from the docker hub: https://hub.docker.com/r/dpokidov/imagemagick and trying to convert bunch of ` jpg files to pdf files ` with `magick mogrify`.  https://imagemagick.org/script/mogrify.php

Executed command: `docker run --entrypoint=identify  -v $(pwd):/imgs dpokidov/imagemagick magick mogrify -format pdf *.jpg`

Error:
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/39536118/221393160-092e2739-2035-49dc-b2c0-ccd56f343961.png">

I'm not sure whether this command is correct or not or what is the reason behind this error.

**Comment by dooman87** [comment]
Hi Rabby,

Thanks for reporting this.

I think the command should go into the `entrypoint` argument so if you'd like to run `magick mogrify` then using Docker it will be something like:

```
docker run --entrypoint=magick -v $(pwd):/imgs dpokidov/imagemagick mogrify -format pdf *.jpg
```

Could you please give it a try and let me know how you go?

**Comment by dooman87** [comment]
Nothing is happening here
