### ISSUE TITLE
Simple alternative

### ISSUE THREAD

**Issue by Tymek** [dooman87/imagemagick-docker#4]
I had success converting files with just:
```
FROM alpine
RUN apk add --no-cache imagemagick
```

Installing this dependency during build takes ~10s. `OK: 101 MiB in 70 packages`

**Comment by dooman87** [comment]
Thanks @Tymek you are right that it's easier. The problem I was trying to solve is having IM7 for specific distro (IM CLI is used from other application) and having specific codecs enabled (WebP + JpegXR). Also, IM might be quite unstable from version to version, so the ability to pick a specific one is nice. 

But, you are right and in most of the cases standard alpine package should do it.

**Comment by dooman87** [comment]
I've just added AVIF support, so it's worthwhile now :)
