### ISSUE TITLE
Upgrade FROM in debian / fedora to always use latest version

### ISSUE THREAD

**Issue by emanuelb** [dooman87/imagemagick-docker#5]
debian use: `debian:stretch-slim` which is debian 9 (latest version is 10) I recommend using `sid-slim` (it's unstable, latest version)
fedora use: 27 (latest version is 32) I recommend using `rawhide` (it's unstable/next-version-in-development) or `latest`

**Comment by dooman87** [comment]
I think we should always maintain set of stable releases. It would be nice to have unstable versions as well, but the build time is already a challenge.

On the side note I'm struggling to keep `fedora` version up to date. The main reason - I'm not using it. Would be great to find volunteers to help maintaining it.
